---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu
    privileged: true
    image: ubuntu:latest
    pre_build_image: false