---
dependency:
   name: galaxy
driver:
   name: ec2
platforms:
  - name: instance
    image_owner: "099720109477"
    image_name: molecule_provisioned
    instance_type: t2.micro
    vpc_subnet_id: vpc-0c96dd0104b1d88ce
    tags:
      nmae: molecule_instance